services:
  app:
    build:
      context: app
      dockerfile: ../Dockerfile-dev
    volumes:
      - ./app:/app
    command: mix phx.server
    ports:
      - 4000:4000
    depends_on:
      - ai_runner

  ai_runner:
    provider:
      type: model
      options:
        model: ai/smollm2