services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/app
    command: /bin/sh -c "mix ecto.create || true && mix phx.server"
    depends_on:
      - ai_runner
    ports:
      - 4000:4000

  ai_runner:
    provider:
      type: model
      options:
        model: ai/smollm2