services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/app
    command: /bin/sh -c "mix ecto.create || true && mix phx.server"
    ports:
      - 4000:4000